# Generated by Django 4.0.5 on 2022-12-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepromo_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userEmail',
            field=models.EmailField(default='shaikh3@gmail.com', max_length=200),
        ),
    ]
