# Generated by Django 4.0.5 on 2022-12-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepromo_main', '0002_user_useremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
