# Generated by Django 4.0.5 on 2022-12-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepromo_main', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.ImageField(default='shaikh3@gmail.com', upload_to='prodImages'),
        ),
    ]
