# Generated by Django 4.0.5 on 2022-12-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepromo_main', '0006_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='mainSender',
            field=models.CharField(default='md shaikh', max_length=150),
        ),
    ]
