# Generated by Django 4.0.5 on 2022-12-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepromo_main', '0005_remove_post_sname_post_senderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderId', models.IntegerField()),
                ('senderName', models.CharField(max_length=150)),
                ('receiverName', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
