# Generated by Django 4.0.5 on 2022-12-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepromo_main', '0007_chat_mainsender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='community',
            field=models.CharField(default='Gaming', max_length=150),
        ),
    ]
